spring:
  threads:
    virtual:
      enabled: true
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Kolkata
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1  
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    listeners:
      ack-mode: MANUAL
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 3
        spring.json.add.type.headers: false
    consumer:
        group-id: ${KAFKA_CONSUMER_GROUP_ID:razorpay-clone-group}
        auto-offset-reset: earliest
        enable-auto-commit: false
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
            spring.json.trusted.packages: "com.pal.dipesh.razorpay.*"
            spring.json.use.type.headers: false
            spring.json.value.default.type: java.util.LinkedHashMap
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.apache.kafka.clients: WARN
    org.apache.kafka.common: WARN

app:
  kafka:
    topics:
      payment: payment.events
      order: order.events
      refund: refund.events
      settlement: settlement.events
  security:
    cookie:                               # Cookie configs are added in common config to create the CookieProperties bean for CookieUtil -> GlobalExceptionHandler
      path: /api/v1/auth                  # cookie only sent to auth endpoints (refresh, logout)
      same-site: Strict                   # blocks browser CSRF for cookie-bearing requests
      secure: ${COOKIE_SECURE:false}      # must be true in prod; override to false only for local http dev
