server:
  port: 9020

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/razorpay-payment-db

payment:
  order:
    default-expiry-minutes: 30

  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL
    method:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80